# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-03 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=30)),
                ('admin_password', models.CharField(max_length=30)),
                ('admin_phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('book_publishing', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=30)),
                ('book_price', models.FloatField()),
                ('book_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookBorrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('private_date', models.DateField()),
                ('if_return', models.BooleanField()),
                ('borrow_num', models.IntegerField(max_length=30)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookRenewal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_date', models.DateField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(auto_now_add=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('booktype_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_type', models.CharField(max_length=30)),
                ('borrow_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('jurisdiction_id', models.AutoField(primary_key=True, serialize=False)),
                ('system_settings', models.BooleanField()),
                ('reader_manage', models.BooleanField()),
                ('boook_manage', models.BooleanField()),
                ('book_return_borrow', models.BooleanField()),
                ('system_search', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LibraryInfo',
            fields=[
                ('lib_id', models.AutoField(primary_key=True, serialize=False)),
                ('lib_name', models.CharField(max_length=30)),
                ('lib_manager', models.CharField(max_length=30)),
                ('lib_phone', models.IntegerField()),
                ('lib_location', models.CharField(max_length=30)),
                ('lib_email', models.CharField(max_length=30)),
                ('lib_url', models.CharField(max_length=30)),
                ('lib_build', models.DateField()),
                ('lib_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('reader_id', models.AutoField(primary_key=True, serialize=False)),
                ('reader_name', models.CharField(max_length=30)),
                ('reader_card', models.CharField(max_length=30)),
                ('reader_phone', models.CharField(max_length=30)),
                ('reader_email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReaderType',
            fields=[
                ('readertype_id', models.AutoField(primary_key=True, serialize=False)),
                ('reader_type', models.CharField(max_length=30)),
                ('reader_borrow_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCard',
            fields=[
                ('transactioncard_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('indate', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='reader_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ReaderType'),
        ),
        migrations.AddField(
            model_name='bookreturn',
            name='reader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reader'),
        ),
        migrations.AddField(
            model_name='bookrenewal',
            name='reader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reader'),
        ),
        migrations.AddField(
            model_name='bookborrow',
            name='reader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reader'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BookStore'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BookType'),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_jurisdiction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Jurisdiction'),
        ),
        migrations.AlterUniqueTogether(
            name='bookreturn',
            unique_together=set([('reader_id', 'book_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='bookrenewal',
            unique_together=set([('reader_id', 'book_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='bookborrow',
            unique_together=set([('reader_id', 'book_id')]),
        ),
    ]
